### ISSUE TITLE
Create tests

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qx-cli#13]
We need a test suite for each API command that ties into the qooxdoo test system and will work with travis. 

@johnspackman Suggestion how we should do this? I haven't created any tests for my qooxdoo code so far (shame on me).

**Comment by johnspackman** [comment]
I dont have many tests so far, but Im using tape for building tests for qooxdoo-compiler; code so far is at https://github.com/qooxdoo/qooxdoo-compiler/tree/master/test.

It's a little tricky because we can't just compare the output of one compile to an "expected" result because lots will (legitimately) change between releases, eg the list of dependencies and order cannot be binary compare.

I think at least initially we need to focus on smaller, specific changes.  For example, qooxdoo-cli tests would test that the compile.json and contrib.json are created and edited properly.  In qooxdoo-compiler, I also check for incremental changes, eg compile once then add an "include", compile again and check there are additions.

**Comment by cboulanger** [comment]
Travis tests have been added a while ago, closing.
